name: vcan-isotp

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref != 'refs/heads/master' && github.ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: vcan0 ISO-TP
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install SocketCAN dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends linux-modules-extra-$(uname -r) can-utils

      - name: Setup project
        run: ./setup.sh

      - name: Build libpanda test artifact
        run: source .venv/bin/activate && /bin/bash -c "scons"

      - name: Setup virtual CAN
        run: |
          ./scripts/build_can_isotp.sh
          ./scripts/set_up_vcan.sh

      - name: Run virtual ISO-TP test
        run: source .venv/bin/activate && /bin/bash -c "pytest -n0 -rs tests/test_isotp_socketcan.py"
